version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    container_name: fatekeeper
    volumes:
      - ./postgres:/var/lib/postgresql/data
